{% set version = "1.6.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rly
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rly_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rly/rly_{{ version }}.tar.gz
  sha256: 22837a41586b6c7afb3d09b1bf71af9189a8bb846a77c55823a2dc98c72b65ad

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-futile.logger
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-r6
    - r-futile.logger

test:
  commands:
    - $R -e "library('rly')"           # [not win]
    - "\"%R%\" -e \"library('rly')\""  # [win]

about:
  home: https://github.com/systemincloud/rly
  license: MIT
  summary: R implementation of the common parsing tools 'lex' and 'yacc'.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rly
# Type: Package
# Title: 'Lex' and 'Yacc'
# Version: 1.6.2
# Date: 2018-09-09
# Authors@R: c(person("Marek", "Jagielski", role = c("aut", "cre", "cph"), email = "marek.jagielski@gmail.com"), person("David M.", "Beazley", role = c("aut", "cph")), person("Yasutaka", "Tanaka", role = c("ctb")), person("Henrico", "Witvliet", role = c("ctb")))
# Author: Marek Jagielski [aut, cre, cph], David M. Beazley [aut, cph], Yasutaka Tanaka [ctb], Henrico Witvliet [ctb]
# Maintainer: Marek Jagielski <marek.jagielski@gmail.com>
# Description: R implementation of the common parsing tools 'lex' and 'yacc'.
# License: MIT + file LICENSE
# URL: https://github.com/systemincloud/rly
# BugReports: https://github.com/systemincloud/rly/issues
# Suggests: testthat
# Depends: R (>= 3.3.0)
# Imports: R6, futile.logger
# RoxygenNote: 5.0.1
# Collate: 'logger.R' 'lex.R' 'yacc.R'
# NeedsCompilation: yes
# Packaged: 2018-09-09 21:23:39 UTC; lupus
# Repository: CRAN
# Date/Publication: 2018-09-10 22:30:03 UTC
