appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZxqE5HBFvIirXsPTTxLAXFJm2/qnnczMMVimDfZXX9BiRcrI4pRhwmmRNUTE7o3zee/ijgBsm8a91bD9GG/k2Uw+ynPHItVxH5iwhw86iYUOA5g29pNokdM19gHciNWVrguf8uNhY9lTFMOjr4vwuwmQwRqFrsMOuGqP9DnzcDxKahqPtMyujmLA5Tftvrv0cKeMzfd7zMohiHrDdwA4Wvh4uUCNku4xoPdsFzV7Obx+0Ubgp3pNuC9oa0WMk4c1cxqrea5/XQPRTYQr2rAR4dFCIsLSi0ypn8/NDWVhbewFGb0T2BVgAmsId55lq+DdnSZ+i6He+ABj/JwwSb0FGCFJ2oNqSqxJj98sLmhqF3MTi7joC8JkRxYtcFZmVgu0veOOP5ZXnJjAUum+a9YM5vxAW9QUmP9rnkIH8lyA1XXKA/j/newM9Nf8oJmSpUZMk36k22NQT5WhHoaskxC2jLmLka7kDCATGRfVvauLHuR5yX9sluxWksElexWcqCeIPJQ+0KxfBhf4uS8f4Ill/BSTezyckpzFlQsXGAj4QnzYWSr/dsDk2iFCrGBflOKb0MKQ/r/T+wDwgLk8/8f3uYHqV2CQhl387OFZwD1FzuX/LKNC4ap/48zOdnmDfp0UktEoVd8hAWGLPuR/Cemnp8FxzmUFU1zwOGgPGplwFMw=}
